packages:
  - "apps/*"
  - "packages/*"


catalog:
  # vitest
  vitest: 3.0.5 # pinned for now as there seems to be a bug with inlineSnapshot on 3.0.4
  vite-tsconfig-paths: 5.1.4
  "@vitejs/plugin-react": 4.3.4
  # testing-library
  "@testing-library/jest-dom": 6.4.6
  "@testing-library/react": 16.2.0
  # react
  react: 19.0.0
  react-dom: 19.0.0
  "@types/react-dom": 19.0.3
  "@types/react": 19.0.8
  "@types/node": 22.13.1
  "@tanstack/react-query": 5.67.1

  # design-system
  "react-hook-form": ^7.54.2
  "@hookform/resolvers": ^3.10.0
  "cmdk": ^1.0.4

  # next
  next: 15.2.2 # exact version, no carrot or tilde
  "@next/bundle-analyzer": 15.2.3 # match exact next version
  typescript: 5.7.3
  tailwindcss: 3.4.17
  postcss: ^8.5.1
  hono: 4.7.1
  "@t3-oss/env-nextjs": 0.12.0
  "@t3-oss/env-core": 0.12.0
  zod: 3.24.1
  svix: 1.45.1
  "@sentry/nextjs": 8.54.0
  "@hono/zod-validator": 0.4.3
  