export enum FileType {
  PDF = 'pdf',
  DOC = 'doc',
  DOCX = 'docx',
  TXT = 'txt',
  CSV = 'csv',
  XLS = 'xls',
  XLSX = 'xlsx',
  PPT = 'ppt',
  PPTX = 'pptx',
  IMG = 'img',
  JPG = 'jpg',
  PNG = 'png',
  SIMPLE = 'simple',
  XML = 'xml',
  JSON = 'json',
  ZIP = 'zip',
  RAR = 'rar',
}
